# Generated by Django 5.2.4 on 2026-03-25 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_departmentprofile_lecturerprofile_studentprofile'),
        ('recruitment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='title',
            field=models.CharField(default='My CV', max_length=100, verbose_name='Tên gợi nhớ (VD: CV Backend Python)'),
        ),
        migrations.AddField(
            model_name='internshippost',
            name='deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Hạn nộp hồ sơ'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cvs', to='accounts.studentprofile'),
        ),
    ]
