# Generated by Django 5.2.4 on 2026-03-25 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0002_cv_title_internshippost_deadline_alter_cv_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('pending', 'Đang chờ duyệt'), ('accepted', 'Trúng tuyển'), ('rejected', 'Không đạt')], default='pending', max_length=20, verbose_name='Trạng thái'),
        ),
    ]
