# Generated by Django 5.2.4 on 2026-03-25 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_departmentprofile_lecturerprofile_studentprofile'),
        ('recruitment', '0003_alter_application_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalInternshipRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, verbose_name='Tên Doanh nghiệp')),
                ('position', models.CharField(max_length=255, verbose_name='Vị trí thực tập')),
                ('contact_person', models.CharField(max_length=255, verbose_name='Người liên hệ')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='Email người liên hệ')),
                ('contact_phone', models.CharField(blank=True, max_length=50, verbose_name='Số điện thoại')),
                ('address', models.TextField(verbose_name='Địa chỉ Doanh nghiệp')),
                ('start_date', models.DateField(verbose_name='Ngày bắt đầu (Dự kiến)')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Ngày kết thúc')),
                ('status', models.CharField(choices=[('pending', 'Chờ phê duyệt'), ('approved', 'Đã phê duyệt'), ('rejected', 'Đã từ chối')], default='pending', max_length=20, verbose_name='Trạng thái')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú thêm')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_requests', to='accounts.studentprofile')),
            ],
        ),
    ]
