# Generated by Django 5.2.4 on 2026-05-02 20:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_alter_user_role_mentorprofile'),
        ('recruitment', '0004_externalinternshiprequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InternshipTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Auto-generated', max_length=255)),
                ('year', models.IntegerField(help_text='Năm thực tập (unique)', unique=True)),
                ('start_date', models.DateField(help_text='Ngày bắt đầu thực tập')),
                ('end_date', models.DateField(help_text='Ngày kết thúc thực tập')),
                ('is_active', models.BooleanField(default=False, help_text='Chỉ 1 kỳ active tại 1 thời điểm')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Kỳ thực tập',
                'verbose_name_plural': 'Kỳ thực tập',
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='DepartmentLecturerAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lecturer_mapping', to='accounts.departmentprofile')),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_mappings', to='accounts.lecturerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ExternalInternshipLecturerConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lecturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_internship_config', to='accounts.lecturerprofile', verbose_name='Giảng viên phụ trách Thực tập Ngoài')),
            ],
            options={
                'verbose_name': 'Cấu hình GV Thực tập Ngoài',
            },
        ),
        migrations.CreateModel(
            name='InternshipAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('application', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignment', to='recruitment.application')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='accounts.departmentprofile')),
                ('external_request', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignment', to='recruitment.externalinternshiprequest')),
                ('lecturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='accounts.lecturerprofile')),
                ('term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='reports.internshipterm', verbose_name='Kỳ thực tập')),
            ],
        ),
        migrations.CreateModel(
            name='FinalReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('content', models.TextField(blank=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='reports/final/')),
                ('is_submitted', models.BooleanField(default=False, help_text='SV đã nộp?')),
                ('is_locked', models.BooleanField(default=False, help_text='Đã khóa - không cho nộp lại?')),
                ('is_late', models.BooleanField(default=False, help_text='Nộp trễ?')),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='final_report', to='reports.internshipassignment')),
            ],
        ),
        migrations.CreateModel(
            name='FinalDeadline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deadline', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('term', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='final_deadline', to='reports.internshipterm')),
            ],
            options={
                'verbose_name': 'Deadline báo cáo tổng kết',
                'verbose_name_plural': 'Deadline báo cáo tổng kết',
            },
        ),
        migrations.CreateModel(
            name='MentorGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('capacity', models.IntegerField(default=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_groups', to='accounts.departmentprofile')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_groups', to='accounts.mentorprofile')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_groups', to='reports.internshipterm')),
            ],
            options={
                'unique_together': {('term', 'department', 'mentor'), ('term', 'department', 'name')},
            },
        ),
        migrations.AddField(
            model_name='internshipassignment',
            name='mentor_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='reports.mentorgroup'),
        ),
        migrations.CreateModel(
            name='TermConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_required_weeks', models.IntegerField(default=5, help_text='Số tuần tối thiểu cần nộp để nộp Final')),
                ('term', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config', to='reports.internshipterm')),
            ],
            options={
                'verbose_name': 'Cấu hình kỳ thực tập',
                'verbose_name_plural': 'Cấu hình kỳ thực tập',
            },
        ),
        migrations.CreateModel(
            name='WeeklyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.PositiveIntegerField()),
                ('title', models.CharField(blank=True, max_length=200)),
                ('content', models.TextField(blank=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='reports/weekly/')),
                ('is_submitted', models.BooleanField(default=False, help_text='SV đã nộp?')),
                ('is_locked', models.BooleanField(default=False, help_text='Đã khóa - không cho nộp lại?')),
                ('is_late', models.BooleanField(default=False, help_text='Nộp trễ?')),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_reports', to='reports.internshipassignment')),
            ],
            options={
                'ordering': ['week_number'],
                'unique_together': {('assignment', 'week_number')},
            },
        ),
        migrations.CreateModel(
            name='LecturerFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('final_report', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='reports.finalreport')),
                ('weekly_report', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='reports.weeklyreport')),
            ],
        ),
        migrations.CreateModel(
            name='FinalReportGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grader_type', models.CharField(choices=[('mentor', 'Mentor'), ('lecturer', 'Lecturer')], max_length=20)),
                ('score', models.DecimalField(decimal_places=2, max_digits=4)),
                ('comment', models.TextField(blank=True)),
                ('graded_at', models.DateTimeField(auto_now_add=True)),
                ('final_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='reports.finalreport')),
                ('lecturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.lecturerprofile')),
                ('mentor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.mentorprofile')),
            ],
            options={
                'unique_together': {('final_report', 'grader_type')},
            },
        ),
        migrations.CreateModel(
            name='WeeklyDeadline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.IntegerField(help_text='1-10')),
                ('deadline', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_deadlines', to='reports.internshipterm')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Deadline tuần',
                'verbose_name_plural': 'Deadline tuần',
                'ordering': ['term', 'week_number'],
                'unique_together': {('term', 'week_number')},
            },
        ),
        migrations.CreateModel(
            name='WeeklyReportGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grader_type', models.CharField(choices=[('mentor', 'Mentor'), ('lecturer', 'Lecturer')], max_length=20)),
                ('score', models.DecimalField(decimal_places=2, max_digits=4)),
                ('comment', models.TextField(blank=True)),
                ('graded_at', models.DateTimeField(auto_now_add=True)),
                ('lecturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.lecturerprofile')),
                ('mentor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.mentorprofile')),
                ('weekly_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='reports.weeklyreport')),
            ],
            options={
                'unique_together': {('weekly_report', 'grader_type')},
            },
        ),
    ]
