# Generated by Django 5.2.4 on 2026-05-03 06:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='finaldeadline',
            name='description',
            field=models.TextField(blank=True, help_text='Mô tả yêu cầu báo cáo tổng kết'),
        ),
        migrations.AddField(
            model_name='finaldeadline',
            name='title',
            field=models.CharField(blank=True, default='Báo cáo Tổng kết Thực tập', help_text='Tiêu đề', max_length=255),
        ),
        migrations.AddField(
            model_name='weeklydeadline',
            name='description',
            field=models.TextField(blank=True, help_text='Mô tả chi tiết yêu cầu tuần này'),
        ),
        migrations.AddField(
            model_name='weeklydeadline',
            name='title',
            field=models.CharField(blank=True, help_text='Tiêu đề bài tập tuần (VD: Cài đặt Linux server)', max_length=255),
        ),
        migrations.CreateModel(
            name='ReportComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Nội dung bình luận')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_comments', to=settings.AUTH_USER_MODEL)),
                ('final_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='reports.finalreport')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='reports.reportcomment')),
                ('weekly_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='reports.weeklyreport')),
            ],
            options={
                'verbose_name': 'Bình luận báo cáo',
                'verbose_name_plural': 'Bình luận báo cáo',
                'ordering': ['created_at'],
            },
        ),
    ]
