# Generated by Django 5.2.4 on 2026-03-25 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_departmentprofile_lecturerprofile_studentprofile'),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internshipassignment',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='internshipassignment',
            name='lecturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='accounts.lecturerprofile'),
        ),
        migrations.AlterField(
            model_name='internshipassignment',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
