# Generated by Django 5.2.4 on 2026-03-25 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_departmentprofile_lecturerprofile_studentprofile'),
        ('reports', '0002_alter_internshipassignment_end_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentLecturerAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lecturer_mapping', to='accounts.departmentprofile')),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_mappings', to='accounts.lecturerprofile')),
            ],
        ),
    ]
