# Generated by Django 5.2.4 on 2026-03-25 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_departmentlecturerassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternshipPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='VD: Học kỳ 1 Năm học 2024-2025', max_length=255)),
                ('start_date', models.DateField(help_text='Ngày bắt đầu thực tập')),
                ('end_date', models.DateField(help_text='Ngày kết thúc thực tập')),
                ('is_active', models.BooleanField(default=False, help_text='Chỉ định 1 kỳ được mở tại một thời điểm')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
