# Generated by Django 5.2.4 on 2026-03-25 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0004_externalinternshiprequest'),
        ('reports', '0004_internshipperiod'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshipassignment',
            name='external_request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignment', to='recruitment.externalinternshiprequest'),
        ),
        migrations.AlterField(
            model_name='internshipassignment',
            name='application',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignment', to='recruitment.application'),
        ),
    ]
