# Generated by Django 5.2.4 on 2026-03-25 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_departmentprofile_lecturerprofile_studentprofile'),
        ('reports', '0005_internshipassignment_external_request_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalInternshipLecturerConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lecturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_internship_config', to='accounts.lecturerprofile', verbose_name='Giảng viên phụ trách Thực tập Ngoài')),
            ],
            options={
                'verbose_name': 'Cấu hình GV Thực tập Ngoài',
            },
        ),
    ]
